first version

diff --git a/shcrypt b/shcrypt
--- a/shcrypt
+++ b/shcrypt
@@ -6,7 +6,7 @@
 
 function usage
 {
-    cat - <<EOF
+    cat - <<'EOF' >&2
 usage:
     shell encrypt: shcrypt -s[cu] <file|-> [<passvar>]
     var encrypt  : shcrypt -v[cu] <varname> [<passvar>]
@@ -16,7 +16,8 @@ usage:
       $ shcrypt -s <<<'myvar="mysecret"' >config.env
 
     * Encrypt to a sourceable shell with variable content protected by password:
-      $ shcrypt -v myvar <<'mysecret' >config.env
+      $ shcrypt -v myvar <<<'mysecret' >config.env
+      if no stdin value, the secret to store will be asked without echoing
 
     * Encrypt to a shell that will output the content when sourced/executed:
       $ shcrypt -t <<<'mysecret' >mysecret.sh
@@ -27,14 +28,14 @@ usage:
             the password is securely passed to openssl through fd
     * -(scu|vcu|tcu) :
             the password is cached in shell local variable <passvar>
-            the password is passed to openssl through -pass:<pass>
+            the password is passed to openssl through -pass pass:<pass>
             /!\ the password will appear in process table when decrypting
 
     * <passvar> : name of the variable to put cached password
                   the password will be cached base64 encoded 
                   in $passvar[$$]
-                  needed if want to share same cache for multiple
-                  env files
+                  needed if want to share same password/cache
+                  for multiple env files
                   default: uuid based varname
 EOF
     exit 1
@@ -44,18 +45,18 @@ function encvar
 {
     read -s -p 'Secret : ' secret
     echo '' >&2
-    echo "$1="'$(openssl enc -aes-256-cbc -md sha512 -d -a <<EOZ 2>/dev/null'"|grep -x '.*'
-$(openssl enc -aes-256-cbc -md sha512 -salt -a <<<"$secret" 2>/dev/null)
+    echo "$1="'$('$ossldec' <<EOZ 2>/dev/null'"|grep -x '.*'
+$($osslenc <<<"$secret" 2>/dev/null)
 EOZ
 ) ||{ echo 'ERROR: Decrypt failed'; }"
 }
 
 function encvarcache
 {
-    read -s -p 'Secret : ' secret;echo >&2
-    echo ': ${'$p$':=$(bash -c \'read -s -p "'$icon$'Password: " p;echo >&2;echo "$p"\'|base64)}'"
-$1="'$(openssl enc -aes-256-cbc -md sha512 -d -a -pass fd:3 <<EOZ 3<<<$(base64 -d <<<"${'$p'}") 2>/dev/null'"|grep -x '.*'
-$(openssl enc -aes-256-cbc -md sha512 -salt -a <<<"$secret" 2>/dev/null)
+    read -s -p 'Secret value: ' secret; echo >&2
+    echo "$cachepass
+$1="'$('$ossldec' -pass fd:3 <<EOZ 3<<<$(base64 -d <<<"${'$p'}") 2>/dev/null'"|grep -x '.*'
+$($osslenc <<<"$secret" 2>/dev/null)
 EOZ
 ) ||{ echo 'ERROR: Decrypt failed';unset $p; }"
 }
@@ -63,65 +64,66 @@ EOZ
 # unsafe: password visible on process table during decrypt
 function encvarcache2
 {
-    read -s -p 'Secret : ' secret
-    echo >&2
-    echo ': ${'$p$':=$(bash -c \'read -s -p "'$icon$'Password: " p;echo >&2;echo "$p"\'|base64)}'"
-$1="'$(openssl enc -aes-256-cbc -md sha512 -d -a -pass pass:$(base64 -d <<<"${'$p'}") <<EOZ 2>/dev/null'"|grep -x '.*'
-$(openssl enc -aes-256-cbc -md sha512 -salt -a <<<"$secret" 2>/dev/null)
+    read -s -p 'Secret value: ' secret; echo >&2
+    echo "$cachepass
+$1="'$('$ossldec' -pass pass:$(base64 -d <<<"${'$p'}") <<EOZ 2>/dev/null'"|grep -x '.*'
+$($osslenc <<<"$secret" 2>/dev/null)
 EOZ
 ) ||{ echo 'ERROR: Decrypt failed';unset $p; }"
 }
 
 function encsh
 {
-    echo 'eval $(openssl enc -aes-256-cbc -md sha512 -d -a <<EOZ 2>/dev/null'"|grep -x '.*'
-$(openssl enc -aes-256-cbc -md sha512 -salt -a -in ${1:--} 2>/dev/null)
+    echo 'eval $('$ossldec' <<EOZ 2>/dev/null'"|grep -x '.*'
+$($osslenc -in ${1:--} 2>/dev/null)
 EOZ
 ) ||{ echo 'ERROR: Decrypt failed'; }"
 }
 
 function encshcache
 {
-    echo ': ${'$p$':=$(bash -c \'read -s -p "'$icon$'Password: " p;echo >&2;echo "$p"\'|base64)}
-eval $(openssl enc -aes-256-cbc -md sha512 -d -a -pass fd:3 <<EOZ 3<<<$(base64 -d <<<"${'$p'}") 2>/dev/null'"|grep -x '.*'
-$(openssl enc -aes-256-cbc -md sha512 -salt -a -in ${1:--} 2>/dev/null)
+    echo "$cachepass"'
+eval $('$ossldec' -pass fd:3 <<EOZ 3<<<$(base64 -d <<<"${'$p'}") 2>/dev/null'"|grep -x '.*'
+$($osslenc -in ${1:--} 2>/dev/null)
 EOZ
 ) ||{ echo 'ERROR: Decrypt failed';unset $p; }"
 }
 
 function encshcache2
 {
-    echo ': ${'$p$':=$(bash -c \'read -s -p "'$icon$'Password: " p;echo >&2;echo "$p"\'|base64)}
-eval $(openssl enc -aes-256-cbc -md sha512 -d -a -pass pass:$(base64 -d <<<"${'$p'}") <<EOZ 2>/dev/null'"|grep -x '.*'
-$(openssl enc -aes-256-cbc -md sha512 -salt -a -in ${1:--} 2>/dev/null)
+    echo "$cachepass"'
+eval $('$ossldec' -pass pass:$(base64 -d <<<"${'$p'}") <<EOZ 2>/dev/null'"|grep -x '.*'
+$($osslenc -in ${1:--} 2>/dev/null)
 EOZ
 ) ||{ echo 'ERROR: Decrypt failed';unset $p; }"
 }
 
 function enctext
 {
-    echo 'openssl enc -aes-256-cbc -md sha512 -d -a <<EOZ 2>/dev/null'"|grep -x '.*' ||{ echo 'ERROR: Decrypt failed';unset $p; }
-$(openssl enc -aes-256-cbc -md sha512 -salt -a -in ${1:--} 2>/dev/null)
+    echo "$ossldec <<EOZ 2>/dev/null|grep -x '.*' ||{ echo 'ERROR: Decrypt failed';unset $p; }
+$($osslenc -in ${1:--} 2>/dev/null)
 EOZ"
 }
 
 function enctextcache
 {
-    echo ': ${'$p$':=$(bash -c \'read -s -p "'$icon$'Password: " p;echo >&2;echo "$p"\'|base64)}
-openssl enc -aes-256-cbc -md sha512 -d -a -pass fd:3 <<EOZ 3<<<$(base64 -d <<<"${'$p'}") 2>/dev/null'"|grep -x '.*' ||{ echo 'ERROR: Decrypt failed';unset $p; }
-$(openssl enc -aes-256-cbc -md sha512 -salt -a -in ${1:--} 2>/dev/null)
+    echo "$cachepass
+$ossldec"' -pass fd:3 <<EOZ 3<<<$(base64 -d <<<"${'$p'}") 2>/dev/null'"|grep -x '.*' ||{ echo 'ERROR: Decrypt failed';unset $p; }
+$($osslenc -a -in ${1:--} 2>/dev/null)
 EOZ"
 }
 
-function enctextcache
+function enctextcache2
 {
-    echo ': ${'$p$':=$(bash -c \'read -s -p "'$icon$'Password: " p;echo >&2;echo "$p"\'|base64)}
-openssl enc -aes-256-cbc -md sha512 -d -a -pass pass:$(base64 -d <<<"${'$p'}") <<EOZ 2>/dev/null'"|grep -x '.*' ||{ echo 'ERROR: Decrypt failed';unset $p; }
-$(openssl enc -aes-256-cbc -md sha512 -salt -a -in ${1:--} 2>/dev/null)
+    echo "$cachepass
+$ossldec"' -pass pass:$(base64 -d <<<"${'$p'}") <<EOZ 2>/dev/null'"|grep -x '.*' ||{ echo 'ERROR: Decrypt failed';unset $p; }
+$($osslenc -in ${1:--} 2>/dev/null)
 EOZ"
 }
 
 PATH='/bin:/usr/bin'
+osslenc='openssl enc -aes-256-cbc -md sha512 -salt -a'
+ossldec='openssl enc -aes-256-cbc -md sha512 -a -d'
 opt=$1
 shift
 p=${2:-__$(sed 's/[-]//g' /proc/sys/kernel/random/uuid 2>/dev/null)}
@@ -129,6 +131,7 @@ p=${2:-__$(sed 's/[-]//g' /proc/sys/kernel/random/uuid 2>/dev/null)}
 : ${p:=__shc_$RANDOM}
 p="$p"'[$$]'
 icon='🔐'
+cachepass=': ${'$p$':=$(bash -c \'read -s -p "'$icon$'Password: " p;echo >&2;echo "$p"\'|base64)}'
 case "$opt" in
     -v) encvar "$@";;
     -vc) encvarcache "$@";;
